### ISSUE TITLE
Provide AUR package

### ISSUE THREAD

**Issue by Airblader** [Airblader/xedgewarp#14]

**Comment by acrisci** [comment]
Just tried it out and it works pretty good :+1:.

Do you want a git package or do you want to wait until a release?

**Comment by Airblader** [comment]
Thanks for the feedback and the bug report! I'll look into it.

I think I prefer git packages when possible. The AUR package has been uploaded at [1] now. I'll have to add it somewhere in the README.

https://aur.archlinux.org/packages/xedgewarp-git/

**Comment by acrisci** [comment]
You don't need to include anything in [base-devel](https://www.archlinux.org/groups/x86_64/base-devel/) as a dependency in your package.

**Comment by Airblader** [comment]
You're right, thanks. Updated.
