### ISSUE TITLE
Pacman style edge warps

### ISSUE THREAD

**Issue by acrisci** [Airblader/xedgewarp#33]
In pacman, when you move off of the left edge of the screen, you end up at the right part of the screen.

I want a sort of "wrap around" effect for my cursor, so if I go to the leftmost edge of the leftmost monitor, I warp to the rightmost edge of the rightmost monitor. And similarly for the top and bottom.

Top/bottom and left/right should be configurable separately.

I don't know if I would actually use this long term, but I might, and it would be really novel to try.

**Comment by Airblader** [comment]
Yeah, I like this idea and I remember a few people having asked about this in various places.

**Comment by Airblader** [comment]
@acrisci I've implemented this on branch `feature-33`. Could you give this a shot and let me know? I don't have multiple outputs right now, so I'm relying on tests and the fake outputs.

Being able to configure this separately is not yet done. I think that's useful, though.

**Comment by acrisci** [comment]
left/right works but up/down doesn't work.

**Comment by Airblader** [comment]
Can you run it with `-l trace` and send me the output of that, please?

**Comment by acrisci** [comment]
```
[src/randr.c:101] TRACE: Found output 639 containing position 2703 / 899
[src/event.c:178] DEBUG: Touching a dead border segment at 2703 / 899.
[src/randr.c:101] TRACE: Found output 639 containing position 2703 / 899
[src/pointer.c:94] TRACE: At position 2703 / 899, there is no more output in direction 4.
[src/pointer.c:102] TRACE: At position 2703 / 899, we cannot cycle to the output in direction 4.
[src/randr.c:101] TRACE: Found output 639 containing position 2703 / 899
[src/event.c:178] DEBUG: Touching a dead border segment at 2703 / 899.
[src/randr.c:101] TRACE: Found output 639 containing position 2703 / 899
[src/pointer.c:94] TRACE: At position 2703 / 899, there is no more output in direction 4.
[src/pointer.c:102] TRACE: At position 2703 / 899, we cannot cycle to the output in direction 4.

```

**Comment by Airblader** [comment]
How are your outputs positioned?

side note: it's too bad we currently don't dump the output positions + sizes on startup. I'll change that.

**Comment by Airblader** [comment]
I just pushed the configurability (`-c none|horizontal|vertical|both`). It now also dumps the outputs found on startup on debug. Maybe you can just try again and if it still doesn't work (to be expected), just also post the part of the log that dumps the outputs.

**Comment by acrisci** [comment]
Still doesn't work.

I have a monitor on the left and right. When I go to the top of the screen, I want to go to the bottom of the same screen.

**Comment by Airblader** [comment]
Oh, now I gotcha! Yeah, that (deliberately) doesn't work. It currently is only meant to work for _multiple_ outputs on the axis. I don't see a reason why not, though. Well, at least no reason that doesn't involve a really exotic setup, anyway.

I'll change this tomorrow. Gotta hit the hay first now.

**Comment by Airblader** [comment]
@acrisci OK, I've changed this now. Please note that I also changed the parameter name to `-t` which you can now also run with "v", "h" (short-hand notation) or no value at all (= "both").

The screen being a torus has a funny feel to it. As a notorious throw-the-pointer-to-the-edge guy, it's not my cup of tea, though. :)

**Comment by acrisci** [comment]
Works good.

I feel so unconstrained by the edges. I'm finding this quite liberating. I think this is probably how the great explorers must have felt when they first realized that the earth was round instead of flat. My cursor is now able to circumnavigate my screen much like Magellan circumnavigated the earth on his ship in his famous voyage to the East Indies.
