### ISSUE TITLE
Warp of mouse pointer not working

### ISSUE THREAD

**Issue by prutheus** [Airblader/xedgewarp#37]
I have xedgewarp installed with my screen setup: at the bottom: 3440x1440, above, left corner, 712x400 ... but when I move the cursor on top of the big screen, where not the little one is above, the cursor seems to be in nowhere, and i must move it left now to get it on the little screen. Not what i have expected ...

**Comment by Airblader** [comment]
Thanks for the report. I'm not sure I understand the output setup correctly. Can you post the output of `xrandr`?

**Comment by prutheus** [comment]
My xrandr setup is: xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP1-2 --mode 712x400_60.00 --pos 0x0 --rotate normal --output DP1-1 --primary --mode 3440x1440 --pos 0x400 --rotate normal --output DP2 --off


EDIT: sorry, now it works, i had an issue!

**Comment by Airblader** [comment]
> EDIT: sorry, now it works, i had an issue!

No worries. Glad it worked out, I'd rather have there be no bug. :-)
