### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by nicoulaj** [Airblader/xedgewarp#43]
Would it be possible do tag a release (for packaging) ? The 1.0 tag is pretty old and I have used the current master for years without any issue.

**Comment by Airblader** [comment]
Hi! Yes, absolutely – sorry that I missed this, so far I've only ever been using my -git package from the AUR and haven't had someone want to package this, so I sort of forgot about ever doing this. I will try to do this soon!

**Comment by Airblader** [comment]
I've tagged a new release and also updated the AUR package. Thanks!

**Comment by nicoulaj** [comment]
Great, thanks! I have created the [stable AUR package](https://aur.archlinux.org/packages/xedgewarp) and added you to co-maintainers.

**Comment by Airblader** [comment]
Thanks, I appreciate it!

**Comment by nmschulte** [comment]
I'd love to see this packaged for Debian -- if I find time soon I'll look into it; not familiar with the maintainer/packaging process there.

**Comment by Airblader** [comment]
That'd be awesome! I don't use any Debian-related system myself, so I can't really help with it, but if you do manage to do this please make sure to send a PR to update the README here. Thanks :-)
