### ISSUE TITLE
Make error: "a2x: Command not found"

### ISSUE THREAD

**Issue by djulien** [Airblader/xedgewarp#44]
The "make" command fails if a2x is not installed (used for generating xedgewarp man pages).  However, a2x is not listed as a dependency.

The solution is to install the asciidocs package before running make:

> sudo apt-get install asciidoc

 (or equivalent package install command)

**Comment by Airblader** [comment]
You're right, it's not listed because it's only a compile time dependency and not a runtime one. Since we list it in the section on compiling from source we should add it there, though.

**Comment by Airblader** [comment]
Fixed with https://github.com/Airblader/xedgewarp/commit/b82f88c57be4aebbeafe50ad18d5458cbe655f8e. Thanks!

**Comment by abdallahalsamman** [comment]
> The "make" command fails if a2x is not installed (used for generating xedgewarp man pages). However, a2x is not listed as a dependency.
> 
> The solution is to install the asciidocs package before running make:
> 
> > sudo apt-get install asciidoc
> 
> (or equivalent package install command)

use `sudo apt --no-install-recommends install asciidoc` so it doesn't install all 700mb worth of unnecessary packages
